#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
  path: /api/login_check
  methods:  [POST]

register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST

api:
  path: /api
  controller: App\Controller\AuthController::api

